spring:
  main:
    web-application-type: none
    banner-mode: off
  ai:
    mcp:
      server:
        name: redmine-mcp-server
        version: 0.1.0
        stdio: true


redmine:
  url: ${REDMINE_URL:}
  api-key: ${REDMINE_API_KEY:}
